import { Injectable } from '@angular/core';
import { Tipologia } from './tipologia';
import { Categoria } from './categoria';
import { Provincia } from './provincia';

@Injectable()
export class MyDataService {
  getTipologia() {
    return [
     new Tipologia(1, 'Lavori' ),
     new Tipologia(2, 'Servizi' ),
     new Tipologia(3, 'Forniture' )
    ];
  }

  getCategoria() {
    return [
		new Categoria('OG1', 1, 'OG1 (Edifici civili e industriali)' ),
		new Categoria('OG2', 1, 'OG2 (Restauro e manutenzione dei beni immobili sottoposti a tutela)' ),
		new Categoria('OG3', 1, 'OG3 (Strade, autostrade, ponti, viadotti, ferrovie, metropolitane)' ),
		new Categoria('OG4', 1, 'OG4 (Opere darte nel sottosuolo)' ),
		new Categoria('OG5', 1, 'OG5 (Dighe)' ),
		new Categoria('OG6', 1, 'OG6 (Acquedotti, gasdotti, oleodotti, opere di irrigazione e di evacuazione)' ),
		new Categoria('OG7', 1, 'OG7 (Opere marittime e lavori di dragaggio)' ),
		new Categoria('OG8', 1, 'OG8 (Opere fluviali, di difesa, di sistemazione idraulica e di bonifica)' ),
		new Categoria('OG9', 1, 'OG9 (Impianti per la produzione di energia elettrica)' ),
		new Categoria('OG10', 1, 'OG10 (Impianti per la trasformazione alta/media tensione e e per la distribuzione di energia elettrica in corrente alternata e continua ed impianti di pubblica illuminazione)' ),
		new Categoria('OG11', 1, 'OG11 (Impianti tecnologici)' ),
		new Categoria('OG12', 1, 'OG12 (Opere ed impianti di bonifica e protezione ambiente)' ),
		new Categoria('OG13', 1, 'OG13 (Opere di ingegneria naturalistica)' ),
		new Categoria('OS1', 1, 'OS1 (Lavori in terra)' ),
		new Categoria('OS2-A', 1, 'OS2-A (Superfici decorate di beni immobili del patrimonio culturale e beni culturali mobili di interesse storico, artistico, archeologico ed etnoantropologico)' ),
		new Categoria('OS2-B', 1, 'OS2-B (Beni culturali mobili di interesse archivistico e librario)' ),
		new Categoria('OS3', 1, 'OS3 (Impianti idrico-sanitario, cucine, lavanderie)' ),
		new Categoria('OS4', 1, 'OS4 (Impianti elettromeccanici trasportatori)' ),
		new Categoria('OS5', 1, 'OS5 (Impianti pneumatici e antintrusione)' ),
		new Categoria('OS6', 1, 'OS6 (Finiture di opere generali in materiali lignei, plastici, metallici e vetrosi)' ),
		new Categoria('OS7', 1, 'OS7 (Finiture di opere generali di natura edile)' ),
		new Categoria('OS8', 1, 'OS8 (Opere di impermeabilizzazione)' ),
		new Categoria('OS9', 1, 'OS9 (Impianti per la segnaletica luminosa e la sicurezza del traffico)' ),
		new Categoria('OS10', 1, 'OS10 (Segnaletica stradale non luminosa)' ),
		new Categoria('OS11', 1, 'OS11 (Apparecchiature strutturali speciali)' ),
		new Categoria('OS12-A', 1, 'OS12-A (Barriere stradali di sicurezza)' ),
		new Categoria('OS12-B', 1, 'OS12-B (Barriere paramassi, fermaneve e simili)' ),
		new Categoria('OS13', 1, 'OS13 (Strutture prefabbricate in cemento armato)' ),
		new Categoria('OS14', 1, 'OS14 (Impianti di smaltimento e recupero dei rifiuti)' ),
		new Categoria('OS15', 1, 'OS15 (Pulizie di acque marine, lacustri, fluviali)' ),
		new Categoria('OS16', 1, 'OS16 (Impianti per centrali di produzione energia elettrica)' ),
		new Categoria('OS17', 1, 'OS17 (Linee telefoniche ed impianti di telefonia)' ),
		new Categoria('OS18-A', 1, 'OS18-A (Componenti strutturali in acciaio)' ),
		new Categoria('OS18-B', 1, 'OS18-B (Componenti per facciate continue)' ),
		new Categoria('OS19', 1, 'OS19 (Impianti di reti di telecomunicazione e di trasmissione dati)' ),
		new Categoria('OS20-A', 1, 'OS20-A (Rilevamenti topografici)' ),
		new Categoria('OS20-B', 1, 'OS20-B (Indagini geognostiche)' ),
		new Categoria('OS21', 1, 'OS21 (Opere strutturali speciali)' ),
		new Categoria('OS22', 1, 'OS22 (Impianti di potabilizzazione e depurazione)' ),
		new Categoria('OS23', 1, 'OS23 (Demolizione di opere)' ),
		new Categoria('OS24', 1, 'OS24 (Verde e arredo urbano)' ),
		new Categoria('OS25', 1, 'OS25 (Scavi archeologici)' ),
		new Categoria('OS26', 1, 'OS26 (Pavimentazioni e sovrastrutture speciali)' ),
		new Categoria('OS27', 1, 'OS27 (Impianti per la trazione elettrica)' ),
		new Categoria('OS28', 1, 'OS28 (Impianti termici e di condizionamento)' ),
		new Categoria('OS29', 1, 'OS29 (Armamento ferroviario)' ),
		new Categoria('OS30', 1, 'OS30 (Impianti interni elettrici, telefonici, radiotelefonici e televisivi)' ),
		new Categoria('OS31', 1, 'OS31 (Impianti per la mobilita sospesa)' ),
		new Categoria('OS32', 1, 'OS32 (Strutture in legno)' ),
		new Categoria('OS33', 1, 'OS33 (Coperture speciali)' ),
		new Categoria('OS34', 1, 'OS34 (Sistemi antirumore per infrastrutture di mobilita' ),
		new Categoria('OS35', 1, 'OS35 (Interventi a basso impatto ambientale)' ),
		new Categoria('50', 2, 'Servizi di riparazione e manutenzione' ),
		new Categoria('51', 2, 'Servizi di installazione (escluso software)' ),
		new Categoria('55', 2, 'Servizi alberghieri, di ristorazione e di vendita al dettaglio' ),
		new Categoria('60', 2, 'Servizi di trasporto' ),
		new Categoria('63', 2, 'Servizi di supporto e ausiliari nel campo dei trasporti' ),
		new Categoria('64', 2, 'Servizi di poste e telecomunicazioni' ),
		new Categoria('65', 2, 'Servizi pubblici' ),
		new Categoria('66', 2, 'Servizi finanziari e assicurativi' ),
		new Categoria('70', 2, 'Servizi immobiliari' ),
		new Categoria('71', 2, 'Servizi architettonici, di costruzione, ingegneria e ispezione' ),
		new Categoria('72', 2, 'Servizi informatici: consulenza, sviluppo di software, Internet e supporto' ),
		new Categoria('73', 2, 'Servizi di ricerca e sviluppo' ),
		new Categoria('75', 2, 'Servizi di pubblica amministrazione e difesa e servizi di previdenza sociale' ),
		new Categoria('76', 2, 'Servizi connessi all industria petrolifera e del gas' ),
		new Categoria('77', 2, 'Servizi connessi all agricoltura, alla silvicoltura, all orticoltura, all acquacoltura e all apicolt' ),
		new Categoria('79', 2, 'Servizi per le imprese: servizi giuridici, di marketing, di consulenza, di reclutamento, di stampa e' ),
		new Categoria('80', 2, 'Servizi di istruzione e formazione' ),
		new Categoria('85', 2, 'Servizi sanitari e di assistenza sociale ' ),
		new Categoria('90', 2, 'Servizi fognari, di raccolta dei rifiuti, di pulizia e ambientali' ),
		new Categoria('92', 2, 'Servizi ricreativi, culturali e sportivi' ),
		new Categoria('98', 2, 'Altri servizi' ),
		new Categoria('03', 3, 'Prodotti dell agricoltura, dell allevamento, della pesca..' ),
		new Categoria('09', 3, 'Prodotti derivati ' ),
		new Categoria('14', 3, 'Prodotti delle miniere, metalli di base e prodotti affini' ),
		new Categoria('15', 3, 'Prodotti alimentari, bevande, tabacco e prodotti affini' ),
		new Categoria('16', 3, 'Macchinari agricoli' ),
		new Categoria('18', 3, 'Indumenti, calzature, articoli da viaggio e accessori' ),
		new Categoria('19', 3, 'Cuoio e tessuti tessili, materiali di plastica e gomma ' ),
		new Categoria('22', 3, 'Stampati e prodotti affini' ),
		new Categoria('24', 3, 'Sostanze chimiche' ),
		new Categoria('30', 3, 'Macchine per ufficio ed elaboratori elettronici, attrezzature e ' ),
		new Categoria('31', 3, 'Macchine e apparecchi, attrezzature e articoli di consumo ' ),
		new Categoria('32', 3, 'Attrezzature per radiodiffusione, televisione, comunicazione, ' ),
		new Categoria('33', 3, 'Apparecchiature mediche, prodotti farmaceutici e per la cura ' ),
		new Categoria('34', 3, 'Attrezzature di trasporto e prodotti ausiliari per il trasporto' ),
		new Categoria('35', 3, 'Attrezzature di sicurezza, antincendio, per la polizia e di ' ),
		new Categoria('37', 3, 'Strumenti musicali, articoli sportivi, giochi, giocattoli, ' ),
		new Categoria('38', 3, 'Attrezzature da laboratorio, ottiche e di precisione' ),
		new Categoria('39', 3, 'Mobili, arredamento, apparecchi ' ),
		new Categoria('41', 3, 'Acqua captata e depurata' ),
		new Categoria('42', 3, 'Macchinari industriali' ),
		new Categoria('43', 3, 'Macchine per l industria mineraria, lo scavo di cave, ' ),
		new Categoria('44', 3, 'Strutture e materiali per costruzione, prodotti ausiliari per ' ),
		new Categoria('45', 3, 'Lavori di costruzione' ),
		new Categoria('48', 3, 'Pacchetti software e sistemi di informazione' )
    ];
  }

  getProvincia() {
    return [
new Provincia('AG', 'Agrigento' ),
new Provincia('AL', 'Alessandria' ),
new Provincia('AN', 'Ancona' ),
new Provincia('AO', 'Aosta' ),
new Provincia('AR', 'Arezzo' ),
new Provincia('AP', 'Ascoli Piceno' ),
new Provincia('AT', 'Asti' ),
new Provincia('AV', 'Avellino' ),
new Provincia('BA', 'Bari' ),
new Provincia('BT', 'Barletta-Andria-Trani' ),
new Provincia('BL', 'Belluno' ),
new Provincia('BN', 'Benevento' ),
new Provincia('BG', 'Bergamo' ),
new Provincia('BI', 'Biella' ),
new Provincia('BO', 'Bologna' ),
new Provincia('BZ', 'Bolzano' ),
new Provincia('BS', 'Brescia' ),
new Provincia('BR', 'Brindisi' ),
new Provincia('CA', 'Cagliari' ),
new Provincia('CL', 'Caltanissetta' ),
new Provincia('CB', 'Campobasso' ),
new Provincia('CI', 'Carbonia-Iglesias' ),
new Provincia('CE', 'Caserta' ),
new Provincia('CT', 'Catania' ),
new Provincia('CZ', 'Catanzaro' ),
new Provincia('CH', 'Chieti' ),
new Provincia('CO', 'Como' ),
new Provincia('CS', 'Cosenza' ),
new Provincia('CR', 'Cremona' ),
new Provincia('KR', 'Crotone' ),
new Provincia('CN', 'Cuneo' ),
new Provincia('EN', 'Enna' ),
new Provincia('FM', 'Fermo' ),
new Provincia('FE', 'Ferrara' ),
new Provincia('FI', 'Firenze' ),
new Provincia('FG', 'Foggia' ),
new Provincia('FC', 'Forlì-Cesena' ),
new Provincia('FR', 'Frosinone' ),
new Provincia('GE', 'Genova' ),
new Provincia('GO', 'Gorizia' ),
new Provincia('GR', 'Grosseto' ),
new Provincia('IM', 'Imperia' ),
new Provincia('IS', 'Isernia' ),
new Provincia('SP', 'La Spezia' ),
new Provincia('AQ', "L'Aquila" ),
new Provincia('LT', 'Latina' ),
new Provincia('LE', 'Lecce' ),
new Provincia('LC', 'Lecco' ),
new Provincia('LI', 'Livorno' ),
new Provincia('LO', 'Lodi' ),
new Provincia('LU', 'Lucca' ),
new Provincia('MC', 'Macerata' ),
new Provincia('MN', 'Mantova' ),
new Provincia('MS', 'Massa-Carrara' ),
new Provincia('MT', 'Matera' ),
new Provincia('ME', 'Messina' ),
new Provincia('MI', 'Milano' ),
new Provincia('MO', 'Modena' ),
new Provincia('MB', 'Monza e della Brianza' ),
new Provincia('NA', 'Napoli' ),
new Provincia('NO', 'Novara' ),
new Provincia('NU', 'Nuoro' ),
new Provincia('OT', 'Olbia-Tempio' ),
new Provincia('OR', 'Oristano' ),
new Provincia('PD', 'Padova' ),
new Provincia('PA', 'Palermo' ),
new Provincia('PR', 'Parma' ),
new Provincia('PV', 'Pavia' ),
new Provincia('PG', 'Perugia' ),
new Provincia('PU', 'Pesaro e Urbino' ),
new Provincia('PE', 'Pescara' ),
new Provincia('PC', 'Piacenza' ),
new Provincia('PI', 'Pisa' ),
new Provincia('PT', 'Pistoia' ),
new Provincia('PN', 'Pordenone' ),
new Provincia('PZ', 'Potenza' ),
new Provincia('PO', 'Prato' ),
new Provincia('RG', 'Ragusa' ),
new Provincia('RA', 'Ravenna' ),
new Provincia('RC', 'Reggio Calabria' ),
new Provincia('RE', 'Reggio Emilia' ),
new Provincia('RI', 'Rieti' ),
new Provincia('RN', 'Rimini' ),
new Provincia('RM', 'Roma' ),
new Provincia('RO', 'Rovigo' ),
new Provincia('SA', 'Salerno' ),
new Provincia('VS', 'Medio Campidano' ),
new Provincia('SS', 'Sassari' ),
new Provincia('SV', 'Savona' ),
new Provincia('SI', 'Siena' ),
new Provincia('SR', 'Siracusa' ),
new Provincia('SO', 'Sondrio' ),
new Provincia('TA', 'Taranto' ),
new Provincia('TE', 'Teramo' ),
new Provincia('TR', 'Terni' ),
new Provincia('TO', 'Torino' ),
new Provincia('OG', 'Ogliastra' ),
new Provincia('TP', 'Trapani' ),
new Provincia('TN', 'Trento' ),
new Provincia('TV', 'Treviso' ),
new Provincia('TS', 'Trieste' ),
new Provincia('UD', 'Udine' ),
new Provincia('VA', 'Varese' ),
new Provincia('VE', 'Venezia' ),
new Provincia('VB', 'Verbano-Cusio-Ossola' ),
new Provincia('VC', 'Vercelli' ),
new Provincia('VR', 'Verona' ),
new Provincia('VV', 'Vibo Valentia' ),
new Provincia('VI', 'Vicenza' ),
    ];
  }

}

